name: Deploy Jekyll site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]
  # Runs on pull requests targeting the default branch
  pull_request:
    branches: [ "main" ]

  # Allows us to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3.7.0
    - name: Set up Node
      uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
      with:
        node-version: 16
        cache: 'npm'
    - name: Install node modules
      run: npm install
    - name: Set up Ruby
      uses: ruby/setup-ruby@ece82769428359c077b5a5eaff268902a303c101
      with:
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Set up Pages
      id: pages
      uses: actions/configure-pages@c5a3e1159e0cbdf0845eb8811bd39e39fc3099c2 # v2.1.3
    - name: Build and test with Rake
      # Only run in pull requests
      if: github.event_name == 'pull_request'
      run: bundle exec rake
    - name: Build with Jekyll
      # Don't run in pull requests
      if: github.event_name != 'pull_request'
      # Outputs to the './_site' directory by default
      run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
      env:
        JEKYLL_ENV: production
    - name: Upload artifact
      # Automatically uploads an artifact from the './_site' directory by default
      uses: actions/upload-pages-artifact@84bb4cd4b733d5c320c9c9cfbc354937524f4d64 # v1.0.10

  # Deployment job
  deploy:
    # Only run on pushes to the default branch
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@f27bcc15848fdcdcc02f01754eb838e44bcf389b # v1.2.9
